
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-14
owner: ucsb-cs156-f24
repo_name: team01-f24-14
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0MzA1ODEy","is_bot":false,"login":"Va1a","name":""},"headRefName":"vala","number":46,"title":"Create ArticlesController class with GET & POST & PUT functionality","url":"https://github.com/ucsb-cs156-f24/team01-f24-14/pull/46"},{"author":{"id":"MDQ6VXNlcjY2MjE4ODE3","is_bot":false,"login":"oviyaseeniraj","name":""},"headRefName":"Oviya-RecRequestTable","number":45,"title":"Closes #20","url":"https://github.com/ucsb-cs156-f24/team01-f24-14/pull/45"}]
